### ISSUE TITLE
fuse not installing

### ISSUE THREAD

**Issue by mirozahorak** [eddow/v-semantic#1]
ERROR  Failed to compile with 1 errors                                                                                                                                                                 This dependency was not found:
* fuse-box-css in ./node_modules/v-semantic/dist/v-semantic.js
To install it, you can run: npm install --save fuse-box-css

runnning npm install --save fuse-box-css gives:
npm ERR! code E404
npm ERR! 404 Not Found: fuse-box-css@latest

**Comment by eddow** [comment]
Yhp, typo of mine - I published a new version but have no means of testing this part now - could you please confirm everything is back in order?

**Comment by mirozahorak** [comment]
Updated. Now my app does not render any output. 
Chrome gives me this error, not sure if this is related to update:

v-semantic.js?b3e6:2 Uncaught Error: Cannot find module "."
    at webpackMissingModule (v-semantic.js?b3e6:2)
    at Object.eval (v-semantic.js?b3e6:2)
    at eval (89:4716)
    at Object.<anonymous> (app.js:1314)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (main.js?1c90:1)
    at Object.<anonymous> (app.js:1074)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
webpackMissingModule @ v-semantic.js?b3e6:2
(anonymous) @ v-semantic.js?b3e6:2
(anonymous) @ 89:4716
(anonymous) @ app.js:1314
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ main.js?1c90:1
(anonymous) @ app.js:1074
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ app.js:976
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
vue.esm.js?efeb:8246 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
client.js?7955:175 [HMR] bundle has 1 warnings
client.js?7955:176 ./node_modules/v-semantic/dist/v-semantic.js
2:25-32 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by eddow** [comment]
Woaw, I never saw this error. May I pretty-please ask you to make a repo with some webpack bundle? I know there are some issues that might appear in between bundlers....

**Comment by mirozahorak** [comment]
i am running this in app created with webpack bundle

**Comment by eddow** [comment]
Better late than never ^^
I replace the bundler by webpack
